### ISSUE TITLE
Feature request: configure a browser shortcut key for creating a bookmark.

### ISSUE THREAD

**Issue by hirusi** [sissbruecker/linkding-extension#1]
Firefox keeps <kbd>Ctrl</kbd><kbd>D</kbd> or <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>D</kbd> as a shortcut to create a new bookmark.

I'd like to be able to have a similar, customizable hotkey that I can call upon and finish creating a bookmark entirely with my keyboard. This is at times less disruptive to whatever I'm doing.

**Comment by onjour** [comment]
I very much second this as well! That would be most useful!

**Comment by sissbruecker** [comment]
Fixed with #5
