### ISSUE TITLE
display currently assigned tags when adding already bookmarked page

### ISSUE THREAD

**Issue by rbauduin** [sissbruecker/linkding-extension#12]
It happens that after I saved a bookmark, I realise I forgot to assign a tag.
To add an aditional tag, I now have to go the the linkding interface and edit the tag.
It would be great if I could simply add the same bookmark, with the dialog displaying the data of the currently existing bookmark. Currently the dialog is empty, and saving the bookmark will override and replace existing information.

**Comment by sissbruecker** [comment]
This has been resolved with #16
