### ISSUE TITLE
Show whether page already bookmarked

### ISSUE THREAD

**Issue by newmedicine** [sissbruecker/linkding-extension#14]
Hi, love your extension, but missing the ability to see whether the page is already bookmarked. For example, I've bookmarked this page, but when I click the "add bookmark" button there is no indication that the page is bookmarked, and the tags I've used aren't displayed.

Is there something wrong with my setup, or is this on a todo list?

Thanks again

Nick

**Comment by vanbeekb** [comment]
I agree with this and would LOVE to see this implemented.

**Comment by sissbruecker** [comment]
This has been resolved with #16
