### ISSUE TITLE
Firefox extension not connecting

### ISSUE THREAD

**Issue by dwdwdan** [sissbruecker/linkding-extension#15]
Hi,
I'm setting up the firefox extension installed from the mozilla store, but the connection keeps failing. I know that the base url is correct (`http://[ip address]:9090`), as opening it in my browser takes me to the login page, and I have copy/pasted the API token so I know that is correct. I have also tried connecting it to the demo site (`https://demo.linkding.link`) which worked completely. I'm guessing there's something wrong with my installation of linkding, any ideas what might be wrong? This is also only the second thing I'm self-hosting, so I'm quite new to setting things like these up.

My server is a VPS from Linode if that makes any difference, and I have nextcloud and a website (using nginx) set up also on the same VPS. I don't currently have https setup for linkding (I can't work out how to to be honest). It is mapped to a subdomain as well, but that's using a masked SRV record but I'm not actually using that for the extension connection.

Thanks for any help

**Comment by AnttiBoman** [comment]
Just double checking that `http://[ip address]:9090` does _not_ include the trailing slash? Also, check #25 and see if you have [HTTPS-Only Mode](https://support.mozilla.org/en-US/kb/https-only-prefs) enabled, as it shouldn't be in your case.

**Comment by dwdwdan** [comment]
The issue was likely HTTPS-Only Mode (Good to learn it applies to extensions too though), but I have since fixed the issue anyway (I have reinstalled onto a different server and it works now)
