### ISSUE TITLE
Google Chrome Extension doesn't work

### ISSUE THREAD

**Issue by blaine07** [sissbruecker/linkding-extension#21]
Everytime I attempt to save a bookmark I get Error saving bookmark: Request error:" When I go to options>save configuration it says it was successful connecting to linkding. I am not sure why it won't ever save a bookmark from the chrome extension
![Screen Shot 2022-07-08 at 6 17 40 AM](https://user-images.githubusercontent.com/63940698/177982321-4d22c7b4-1ee4-47ef-8fd4-d5a453eadb6a.png)
?

**Comment by sissbruecker** [comment]
I'm afraid there's not much I can do here to debug this. I'd guess the linkding URL is not configured correctly, or there's an issue with HTTPS.
