### ISSUE TITLE
Check for existing bookmark

### ISSUE THREAD

**Issue by rickcecil** [sissbruecker/linkding-extension#26]
Any chance this could be updated to check for an existing bookmark of the current page? The bookmarklet does this and it is great, but the bookmarklet doesn't work on every site. Thoughts?

**Comment by sissbruecker** [comment]
This should already work. If the URL is already bookmarked, then:
- the title changes to "Edit bookmark"
- you get a warning that you are editing an existing bookmark
- tags, title and description are pre-filled from the existing bookmark

![Bildschirmfoto 2022-09-21 um 18 52 17](https://user-images.githubusercontent.com/357820/191565455-88f332bb-2b0e-4a0f-9d4f-850ef961dc0f.png)

**Comment by rickcecil** [comment]
So it does indeed work. At least it is here on my laptop. Gotta figure out what I was seeing my desktop that prompted me to file the ticket. Likely an error between the keyboard and the seat. Apologies!
