### ISSUE TITLE
Mismatch on detecting existing bookmarks

### ISSUE THREAD

**Issue by sebw** [sissbruecker/linkding-extension#28]
Hi,

I started using linkding not an hour ago. I love it! Especially the injector add-on.

I bookmarked this URL with two tags (iOS, bookmark): https://github.com/sissbruecker/linkding/blob/master/docs/how-to.md

Now if I go back to the main project page https://github.com/sissbruecker/linkding/ and want to bookmark the project page, potentially with different tags, the extension actually pulls the two tags of the how-to URL and the description.

If I edit the new bookmark (deleted the unrelated tags, change the description) I end up with 2 bookmarks.

This can give a false impression that specific URL is already bookmarked while it's not.

Is this by design? Or something I can configure (just like bitwarden, host matching rules, full URL matching, etc.)

Thanks!

**Comment by sebw** [comment]
So if I try to bookmark https://github.com it also pulls a completely unrelated tag.

I checked the `bookmark/check` endpoint and this looks like the most accurate (but more expensive) approach.

**Comment by sissbruecker** [comment]
Right, the other issue with that endpoint is that it additionally scrapes the website metadata, which takes longer. Maybe this could be combined to show the scraped metadata in the input fields like the bookmarklet does. The current solution only shows the title from the tab, but then uses the scraped metadata anyway which can be misleading.
