### ISSUE TITLE
Graphical feedback of linkding bookmark button

### ISSUE THREAD

**Issue by pitah81** [sissbruecker/linkding-extension#30]
It would be nice if the linkding bookmark button would show some kind of graphical feedback if the website you're on has already been bookmarked.

**Comment by GAntoine** [comment]
Hey @pitah81, I added this as part of #46 using [`setBadgeText`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/setBadgeText), so a bookmarked page now displays a small yellow star. Take a look at the PR and let me know what you think!
