### ISSUE TITLE
[Feature request] Save links from right click menu

### ISSUE THREAD

**Issue by arvaid** [sissbruecker/linkding-extension#35]
It would be nice to be able to save links without opening them first, e.g. by right clicking on them and choosing save via linkding.

**Comment by GAntoine** [comment]
Hey @arvaid, #46 adds an entry to the context menu to quick-add a link, and shows a notification when added. I'd really appreciate your thoughts on it!

**Comment by arvaid** [comment]
Thanks, that's great!
