### ISSUE TITLE
Extension sending all clicked links to server

### ISSUE THREAD

**Issue by Q3x7Dvh** [sissbruecker/linkding-extension#36]
**Issue:** The extension in Firefox is sending all clicked links to my Linkding server, completely unrelated to use of the address bar to search.
**Extension version:** v1.5
**Browser:** Firefox 110.0.1 (64-bit)
**OS:** Windows 10
**Server version:** v1.17.2

### Details:

I first noticed this when looking through the server logs and seeing the text I had just searched DuckDuckGo for. 

Using the `ld` shortcut in the address bar works as expected, but any link I click or address I enter in the address bar is sent to the `/api/bookmarks/check/` endpoint. I'm essentially key logging myself in the browser 😄

See below for the network traffic from the extension (Note: I've mistakenly referred to the address bar as the Omnibar in the image):
![Linkding extension issue](https://user-images.githubusercontent.com/117139721/222592395-8ce0e8e9-5689-4454-95ae-cb5c62c5b0f1.png)

**Comment by Q3x7Dvh** [comment]
I dug into the codebase and realised that this is likely by design: @sissbruecker's commit b6fd7a9 adds the caching feature.

I disabled this precaching and tested it: don't see much of a speed difference. Is the precaching necessary? Grabbing the page data when you are about to bookmark it populates very quickly for me.

Thanks for developing linkding and this extension, I'm really happy with it so far!

**Comment by maxheadroom** [comment]
I just noticed the same. I think this feature is a red flag. It would allow the person hosting the LinkDing to see all browsed pages of the users. This seems rather excessive.

**Comment by maximecurioni** [comment]
I spent some time this evening trying to debug why every visit to a local server would log two simultaneous requests, one with my IP and another with the IP of the server running linkding. Fortunately, I found this thread which clearly explains the problem, thanks to @Q3x7Dvh tracing it down to #32.

I believe that this is a fundamental privacy issue: it is not self-evident that using the linkding extension implies that every page load is also attempted by the linkding server. In my opinion, this should be disabled by default. For now, I will limit my use of the linkding extension to a separate Chrome sandbox profile.

At the very least, the pre-caching mechanism referenced in #32 should not be performed on every URL load, but only when clicking attempting to add the bookmark. I understand that this may introduce latency in certain cases, but it would prevent spamming server logs on mere navigation.

@sissbruecker please let us know your thoughts. If an easy fix is not possible, I'd be willing to work with you on a PR to improve the current situation.

**Comment by Q3x7Dvh** [comment]
I'm running a custom build of the Firefox extension with pre-caching disabled now.

I agree with @maximecurioni: a default-off toggle in the extension settings seems like a good way forward.

@sissbruecker: I'm happy to put together a PR if you are okay with this approach.

It would be nice to not have to be running an extension with a scary warning banner 😄 

![image](https://user-images.githubusercontent.com/117139721/231947717-0b5927bb-f954-469c-ad00-02f639c06cab.png)

**Comment by sissbruecker** [comment]
Yeah, I'm fine with making this opt-in using an option. Personally I love that title and description are already there when I open the popup. The privacy concerns seem a bit overblown, given that this is intended to be a self-hosted app, but there's no point in arguing about it. 

If someone wants to work on this, please go ahead.

**Comment by maximecurioni** [comment]
@Q3x7Dvh would you like to send your custom extension changes to PR, or should we start to work on a separate effort?

**Comment by fspoettel** [comment]
IMHO this is a big issue for multi-user setups which Linkding _does_ allow currently. I've stopped using Linkding after seeing some of my family members private search results that I was not aware at all are being persisted in the server logs.

As a side note, this feature appears to significantly increase resource usage of the service as well.

**Comment by Q3x7Dvh** [comment]
> @Q3x7Dvh would you like to send your custom extension changes to PR, or should we start to work on a separate effort?

@maximecurioni, I've submitted a PR now (PR #38).

**Comment by sissbruecker** [comment]
Resolved as part of https://github.com/sissbruecker/linkding-extension/pull/38

**Comment by maximecurioni** [comment]
Just tested the latest extension v1.6 and it works as expected.

Thanks @sissbruecker and @Q3x7Dvh!
