### ISSUE TITLE
pulling title and description doesn't work

### ISSUE THREAD

**Issue by X2theL** [sissbruecker/linkding-extension#37]
Hi, 
I just set up linkding on a vserver using just docker and Caddy as a reverse proxy. In nftables I allowed all outgoing traffic but it seems like linkding can't go through anyway since the automatic pulling of title and description always times out. Is there anything I have to do in docker (or anywhere else) to fix that?

**Comment by sissbruecker** [comment]
Sorry, I can't provide support for setting up the host environment. Usually you don't have to configure anything in Docker to get this to work, so it's likely an issue with the host. For debugging this you could also try some other tool such as cURL and see if you can get that to work.
