### ISSUE TITLE
[Feature Request] Option to hide unused tags from autocomplete

### ISSUE THREAD

**Issue by adamshand** [sissbruecker/linkding-extension#45]
I have a large bookmark collection and periodically I go through and tidy things up.  For example, perhaps I have the tags photos and images and decide that I only want one.  Or maybe I have tutorial and howto?  So I'll go through and consolidate tags.

But the extension offers tags via autocomplete that no longer have any links.  Which means that when I next go to add a tutorial I have to remember how I changed this (did I move the howtos to tutorial or the other way around?) and it's easy to make a mess again.

Thanks again for the great project!

**Comment by glottisfaun0000** [comment]
in settings > admin > tags you can deleted unused tags

**Comment by adamshand** [comment]
Thank you, I missed that!
