### ISSUE TITLE
Maybe conflict between linkding chrome extension and archivebox self-hosted website

### ISSUE THREAD

**Issue by treejiang** [sissbruecker/linkding-extension#57]
Linkding is one of my favorate software. and I've setup the self-hosted linkding server and extensions for Firefox and  Chrome, it works well.

Possible Bug

- After I setup a self-hosted (docker-comopse) archivebox server and use the browser to visite the archivebox site, strange things happen: 
- always ask for re-login for each webpage click , like cookie missing, both firefox and chrome on a X86 Win10 PC.
- Then I change to Edge (without Linkding extension on the same pc) to browse, it works OK.
- I use the android tablet Firefox to browse, it works well, too.
**- So I consider the fault is related to the specific browser configuration.**

Possible Bug Location

- When I reset the Chrome ( all extension disabled) , It works well. Then I enable extensions  one by one to locate the conflict. When I turn on Linkding extension, **the conflict** (ask for login with username and password for each webpage on self-hosted archivebox server) **happen again** (like cookie missing etc).
- When I reset the Firefox ( all extension disabled). It work well. When I enable extensions one by one, even turn on the linkding extension, It still **works well**.

And I didn't find anything other websites happen this way.  Linkding extension works OK both on Chrome and Firefox.

So maybe it's a linkding extension bug, and maybe some compatible issues of archivebox( **but I can't find any information about this issue**).

FYI.

**Comment by treejiang** [comment]
Chrome Extension solution:

Extension configuration: 
Authorized websites (can read and modify data on website) OPTION:

- [x] only When Click
- [ ] on specific website
- [ ] any websites

Then it works OK.

**Comment by sissbruecker** [comment]
It sounds like there is a conflict between session cookies used by linkding and archivebox, possibly because both are Django apps and maybe both use the same default cookie name. If you still encounter this I would suggest to open an issue in the main repo, as it's unlikely that this is related to the extension.
