### ISSUE TITLE
Add bookmark shortcut does not work on Mac

### ISSUE THREAD

**Issue by shantheone** [sissbruecker/linkding-extension#58]
Hi!

I'm a happy user of Linkding for a long time now but there is one little thing that bothers me: the Firefox extensoins shortcut (Alt + Shift + L) to add a new bookmark does not work on Mac, it has never worked. After searching through the issues here, I could not find this reported so here we go:

MacOS version: 14.2.1
Firefox version: 121.0 (64-bit)
Firefox extension version: 1.8.0
Linkding version installed: 1.23.1

I tried to use both Alt keys, neither of them works.

It is an admittedly low priority issue, but can be easily reproduced and hopefully an easy fix as well.

Thank you for this really useful app!

**Comment by jonathan-s** [comment]
@shantheone, After having it pointed out in the PR attached above, the shortcut works on mac in firefox. I'm having the same configuration as you do. Could perhaps be a keyboard shortcut collision. The keys on the mac being pressed are Option + Shift + L.

**Comment by jonathan-s** [comment]
No worries :)
