### ISSUE TITLE
[Feature request] Pick up description from <meta property="og:description"> 

### ISSUE THREAD

**Issue by jonathan-s** [sissbruecker/linkding-extension#59]
Pre-fill the description from this page value.

**Comment by sissbruecker** [comment]
Scraping of the metadata happens on the server: https://github.com/sissbruecker/linkding/blob/ba3e581d8581f673ba1034818a56c25d59375839/bookmarks/services/website_loader.py#L30

You might want to open your issue in the main repo instead.
