### ISSUE TITLE
Allow saving bookmarks as unread by default

### ISSUE THREAD

**Issue by yeskunall** [sissbruecker/linkding-extension#68]
I was wondering if you’d be open to adding an option to save a bookmark as unread by default.

<details><summary>Screenshot</summary>
<p>

<img width="399" alt="CleanShot 2024-03-15 at 02 18 42@2x" src="https://github.com/sissbruecker/linkding-extension/assets/14703164/c9699f43-4396-4219-b2f4-73791021d337">

</p>
</details> 

The extension already allows you to add a default tags, so in a way what I’m asking for is already possible. But that involves creating a dedicated bookmark, then filtering by it.

__PS__: Thanks for the work on linkding (and this extension!)

**Comment by sissbruecker** [comment]
Seems reasonable, I'd be open to contributions.
