### ISSUE TITLE
Case insensitive search for tag

### ISSUE THREAD

**Issue by justinkelly** [sissbruecker/linkding-extension#70]
If my tags have the first letter capitalised - such as `Version control` 
- in the extension when adding a new booking I would like to just be able to type 'v' and a case insensitive search of my tags is done

currently if I type `v` then `Version control` is not shown in the drop down tags menu

`v`
![image](https://github.com/sissbruecker/linkding-extension/assets/249520/80eb9375-9dcb-41f2-a9d9-7d26328b3f76)

`V`
![image](https://github.com/sissbruecker/linkding-extension/assets/249520/c96faaa5-9ed2-4098-8abf-9170b5dfdbf7)

Thanks !!!!!!!!!!!!!!!!!!!!

**Comment by sissbruecker** [comment]
Should be resolved with https://github.com/sissbruecker/linkding-extension/pull/73

**Comment by justinkelly** [comment]
thanks @sissbruecker and @FireFingers21 !!!!!
