### ISSUE TITLE
Chrome extension: Cannot save bookmarks with empty title or description

### ISSUE THREAD

**Issue by eli-yip** [sissbruecker/linkding-extension#88]
### Environment:

Linkding version: 1.36.0 (latest)
Chrome version: 129.0.6668.90
Extension version: 1.12.0

### Issue Description:

When using the linkding Chrome extension, there's a bug with saving bookmarks. If the initial title or description fetched from the webpage is empty, attempting to save results in an error stating that the title or description cannot be `null`. However, if I input random content and then delete it, I am able to save the bookmark successfully.

### Expected Behavior:

It should be possible to save bookmarks even when the title or description fields are empty.

### Additional Information:

This issue seems to have appeared within the last month; it was functioning correctly before.

**Comment by sissbruecker** [comment]
That was fixed just yesterday: https://github.com/sissbruecker/linkding-extension/pull/86

Still needs to be released.
